#!/bin/sh

MSG=`awk '{printf("%s",$0)}' $1`


if [[ $MSG =~ ^(\[INLONG-[0-9]{1,100}\])(\[[a-zA-Z]+\]) ]]
then
	echo "\033[32m commit success! \033[0m"
else
        echo  "Format:
[INLONG-XYZ][Component] Commmmit Message
where *XYZ* should be replaced by the actual issue number, *Component* is the module name of InLong
Eg:
[INLONG-3160][Manager] Upgrade to jackson without cve"
	exit 1
fi

