@rem
@rem Licensed to the Apache Software Foundation (ASF) under one or more
@rem contributor license agreements.  See the NOTICE file distributed with
@rem this work for additional information regarding copyright ownership.
@rem The ASF licenses this file to You under the Apache License, Version 2.0
@rem (the "License"); you may not use this file except in compliance with
@rem the License.  You may obtain a copy of the License at
@rem <p>
@rem http://www.apache.org/licenses/LICENSE-2.0
@rem <p>
@rem Unless required by applicable law or agreed to in writing, software
@rem distributed under the License is distributed on an "AS IS" BASIS,
@rem WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@rem See the License for the specific language governing permissions and
@rem limitations under the License.
@rem

@echo off
set version=%1
set outputDirectory=%2

md %outputDirectory%\com\tencent\tubemq\server\common
set tubeServerVersion=%outputDirectory%\com\tencent\tubemq\server\common\TubeServerVersion.java"

echo /* > %tubeServerVersion%
echo  * Generated by src/saveServerVersion.cmd>> %tubeServerVersion%
echo  */>> %tubeServerVersion%
echo package com.tencent.tubemq.server.common;>> %tubeServerVersion%
echo,>> %tubeServerVersion%
echo public class TubeServerVersion {>> %tubeServerVersion%
echo     public static final String BROKER_VERSION = "%version%";>> %tubeServerVersion%
echo } >> %tubeServerVersion%

