/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.inlong.audit.tool.metric;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * MetricData is a data transfer object (DTO) that encapsulates the metrics
 * generated by the Audit Tool. It holds information about data loss rates and
 * any triggered alerts, ready to be processed by a MetricReporter.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class MetricData {

    /**
     * The Inlong Group ID, used as a primary dimension for metrics.
     */
    private String groupId;

    /**
     * The Inlong Stream ID, used as a secondary dimension for metrics.
     */
    private String streamId;

    /**
     * The calculated data loss rate. This can be null if not applicable
     * for a given report.
     */
    private Double dataLossRate;

    /**
     * Information about a triggered alert. This can be null if no alert
     * was triggered for this metric data point.
     */
    private AlertInfo alertInfo;

    /**
     * A nested static class to hold details about a specific alert.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class AlertInfo {

        /**
         * The type of the alert, for example, "DATA_LOSS_SEVERE" or "DELAY_HIGH".
         * This will be used as a label in the monitoring system.
         */
        private String alertType;
    }
}
