/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventProto struct {
	RebalanceId int64 `protobuf:"varint,1,opt,name=rebalanceId,proto3" json:"rebalanceId,omitempty"`
	OpType      int32 `protobuf:"varint,2,opt,name=opType,proto3" json:"opType,omitempty"`
	Status      int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// consumerId@group-brokerId:host:port-topic:partitionId
	SubscribeInfo        []string `protobuf:"bytes,4,rep,name=subscribeInfo,proto3" json:"subscribeInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventProto) Reset()         { *m = EventProto{} }
func (m *EventProto) String() string { return proto.CompactTextString(m) }
func (*EventProto) ProtoMessage()    {}
func (*EventProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *EventProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventProto.Unmarshal(m, b)
}
func (m *EventProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventProto.Marshal(b, m, deterministic)
}
func (m *EventProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventProto.Merge(m, src)
}
func (m *EventProto) XXX_Size() int {
	return xxx_messageInfo_EventProto.Size(m)
}
func (m *EventProto) XXX_DiscardUnknown() {
	xxx_messageInfo_EventProto.DiscardUnknown(m)
}

var xxx_messageInfo_EventProto proto.InternalMessageInfo

func (m *EventProto) GetRebalanceId() int64 {
	if m != nil {
		return m.RebalanceId
	}
	return 0
}

func (m *EventProto) GetOpType() int32 {
	if m != nil {
		return m.OpType
	}
	return 0
}

func (m *EventProto) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *EventProto) GetSubscribeInfo() []string {
	if m != nil {
		return m.SubscribeInfo
	}
	return nil
}

type EnableBrokerFunInfo struct {
	EnableConsumeAuthenticate bool     `protobuf:"varint,1,opt,name=enableConsumeAuthenticate,proto3" json:"enableConsumeAuthenticate,omitempty"`
	EnableConsumeAuthorize    bool     `protobuf:"varint,2,opt,name=enableConsumeAuthorize,proto3" json:"enableConsumeAuthorize,omitempty"`
	EnableProduceAuthenticate bool     `protobuf:"varint,3,opt,name=enableProduceAuthenticate,proto3" json:"enableProduceAuthenticate,omitempty"`
	EnableProduceAuthorize    bool     `protobuf:"varint,4,opt,name=enableProduceAuthorize,proto3" json:"enableProduceAuthorize,omitempty"`
	EnableVisitTokenCheck     bool     `protobuf:"varint,5,opt,name=enableVisitTokenCheck,proto3" json:"enableVisitTokenCheck,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *EnableBrokerFunInfo) Reset()         { *m = EnableBrokerFunInfo{} }
func (m *EnableBrokerFunInfo) String() string { return proto.CompactTextString(m) }
func (*EnableBrokerFunInfo) ProtoMessage()    {}
func (*EnableBrokerFunInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *EnableBrokerFunInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableBrokerFunInfo.Unmarshal(m, b)
}
func (m *EnableBrokerFunInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableBrokerFunInfo.Marshal(b, m, deterministic)
}
func (m *EnableBrokerFunInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableBrokerFunInfo.Merge(m, src)
}
func (m *EnableBrokerFunInfo) XXX_Size() int {
	return xxx_messageInfo_EnableBrokerFunInfo.Size(m)
}
func (m *EnableBrokerFunInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableBrokerFunInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EnableBrokerFunInfo proto.InternalMessageInfo

func (m *EnableBrokerFunInfo) GetEnableConsumeAuthenticate() bool {
	if m != nil {
		return m.EnableConsumeAuthenticate
	}
	return false
}

func (m *EnableBrokerFunInfo) GetEnableConsumeAuthorize() bool {
	if m != nil {
		return m.EnableConsumeAuthorize
	}
	return false
}

func (m *EnableBrokerFunInfo) GetEnableProduceAuthenticate() bool {
	if m != nil {
		return m.EnableProduceAuthenticate
	}
	return false
}

func (m *EnableBrokerFunInfo) GetEnableProduceAuthorize() bool {
	if m != nil {
		return m.EnableProduceAuthorize
	}
	return false
}

func (m *EnableBrokerFunInfo) GetEnableVisitTokenCheck() bool {
	if m != nil {
		return m.EnableVisitTokenCheck
	}
	return false
}

type AuthenticateInfo struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce                int32    `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	OthParams            string   `protobuf:"bytes,4,opt,name=othParams,proto3" json:"othParams,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateInfo) Reset()         { *m = AuthenticateInfo{} }
func (m *AuthenticateInfo) String() string { return proto.CompactTextString(m) }
func (*AuthenticateInfo) ProtoMessage()    {}
func (*AuthenticateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{2}
}

func (m *AuthenticateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateInfo.Unmarshal(m, b)
}
func (m *AuthenticateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateInfo.Marshal(b, m, deterministic)
}
func (m *AuthenticateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateInfo.Merge(m, src)
}
func (m *AuthenticateInfo) XXX_Size() int {
	return xxx_messageInfo_AuthenticateInfo.Size(m)
}
func (m *AuthenticateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateInfo proto.InternalMessageInfo

func (m *AuthenticateInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *AuthenticateInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AuthenticateInfo) GetNonce() int32 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *AuthenticateInfo) GetOthParams() string {
	if m != nil {
		return m.OthParams
	}
	return ""
}

func (m *AuthenticateInfo) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type MasterCertificateInfo struct {
	AuthInfo             *AuthenticateInfo `protobuf:"bytes,1,opt,name=authInfo,proto3" json:"authInfo,omitempty"`
	AuthorizedToken      string            `protobuf:"bytes,2,opt,name=authorizedToken,proto3" json:"authorizedToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MasterCertificateInfo) Reset()         { *m = MasterCertificateInfo{} }
func (m *MasterCertificateInfo) String() string { return proto.CompactTextString(m) }
func (*MasterCertificateInfo) ProtoMessage()    {}
func (*MasterCertificateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{3}
}

func (m *MasterCertificateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterCertificateInfo.Unmarshal(m, b)
}
func (m *MasterCertificateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterCertificateInfo.Marshal(b, m, deterministic)
}
func (m *MasterCertificateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterCertificateInfo.Merge(m, src)
}
func (m *MasterCertificateInfo) XXX_Size() int {
	return xxx_messageInfo_MasterCertificateInfo.Size(m)
}
func (m *MasterCertificateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterCertificateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MasterCertificateInfo proto.InternalMessageInfo

func (m *MasterCertificateInfo) GetAuthInfo() *AuthenticateInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

func (m *MasterCertificateInfo) GetAuthorizedToken() string {
	if m != nil {
		return m.AuthorizedToken
	}
	return ""
}

type MasterAuthorizedInfo struct {
	VisitAuthorizedToken int64    `protobuf:"varint,1,opt,name=visitAuthorizedToken,proto3" json:"visitAuthorizedToken,omitempty"`
	AuthAuthorizedToken  string   `protobuf:"bytes,2,opt,name=authAuthorizedToken,proto3" json:"authAuthorizedToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterAuthorizedInfo) Reset()         { *m = MasterAuthorizedInfo{} }
func (m *MasterAuthorizedInfo) String() string { return proto.CompactTextString(m) }
func (*MasterAuthorizedInfo) ProtoMessage()    {}
func (*MasterAuthorizedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{4}
}

func (m *MasterAuthorizedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterAuthorizedInfo.Unmarshal(m, b)
}
func (m *MasterAuthorizedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterAuthorizedInfo.Marshal(b, m, deterministic)
}
func (m *MasterAuthorizedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterAuthorizedInfo.Merge(m, src)
}
func (m *MasterAuthorizedInfo) XXX_Size() int {
	return xxx_messageInfo_MasterAuthorizedInfo.Size(m)
}
func (m *MasterAuthorizedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterAuthorizedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MasterAuthorizedInfo proto.InternalMessageInfo

func (m *MasterAuthorizedInfo) GetVisitAuthorizedToken() int64 {
	if m != nil {
		return m.VisitAuthorizedToken
	}
	return 0
}

func (m *MasterAuthorizedInfo) GetAuthAuthorizedToken() string {
	if m != nil {
		return m.AuthAuthorizedToken
	}
	return ""
}

type MasterBrokerAuthorizedInfo struct {
	VisitAuthorizedToken string   `protobuf:"bytes,1,opt,name=visitAuthorizedToken,proto3" json:"visitAuthorizedToken,omitempty"`
	AuthAuthorizedToken  string   `protobuf:"bytes,2,opt,name=authAuthorizedToken,proto3" json:"authAuthorizedToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterBrokerAuthorizedInfo) Reset()         { *m = MasterBrokerAuthorizedInfo{} }
func (m *MasterBrokerAuthorizedInfo) String() string { return proto.CompactTextString(m) }
func (*MasterBrokerAuthorizedInfo) ProtoMessage()    {}
func (*MasterBrokerAuthorizedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{5}
}

func (m *MasterBrokerAuthorizedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterBrokerAuthorizedInfo.Unmarshal(m, b)
}
func (m *MasterBrokerAuthorizedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterBrokerAuthorizedInfo.Marshal(b, m, deterministic)
}
func (m *MasterBrokerAuthorizedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterBrokerAuthorizedInfo.Merge(m, src)
}
func (m *MasterBrokerAuthorizedInfo) XXX_Size() int {
	return xxx_messageInfo_MasterBrokerAuthorizedInfo.Size(m)
}
func (m *MasterBrokerAuthorizedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterBrokerAuthorizedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MasterBrokerAuthorizedInfo proto.InternalMessageInfo

func (m *MasterBrokerAuthorizedInfo) GetVisitAuthorizedToken() string {
	if m != nil {
		return m.VisitAuthorizedToken
	}
	return ""
}

func (m *MasterBrokerAuthorizedInfo) GetAuthAuthorizedToken() string {
	if m != nil {
		return m.AuthAuthorizedToken
	}
	return ""
}

type DataStorePath struct {
	RecordId             int32    `protobuf:"varint,1,opt,name=recordId,proto3" json:"recordId,omitempty"`
	IsActive             bool     `protobuf:"varint,2,opt,name=isActive,proto3" json:"isActive,omitempty"`
	IsDefPath            bool     `protobuf:"varint,3,opt,name=isDefPath,proto3" json:"isDefPath,omitempty"`
	DataPath             string   `protobuf:"bytes,4,opt,name=dataPath,proto3" json:"dataPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataStorePath) Reset()         { *m = DataStorePath{} }
func (m *DataStorePath) String() string { return proto.CompactTextString(m) }
func (*DataStorePath) ProtoMessage()    {}
func (*DataStorePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{6}
}

func (m *DataStorePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataStorePath.Unmarshal(m, b)
}
func (m *DataStorePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataStorePath.Marshal(b, m, deterministic)
}
func (m *DataStorePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataStorePath.Merge(m, src)
}
func (m *DataStorePath) XXX_Size() int {
	return xxx_messageInfo_DataStorePath.Size(m)
}
func (m *DataStorePath) XXX_DiscardUnknown() {
	xxx_messageInfo_DataStorePath.DiscardUnknown(m)
}

var xxx_messageInfo_DataStorePath proto.InternalMessageInfo

func (m *DataStorePath) GetRecordId() int32 {
	if m != nil {
		return m.RecordId
	}
	return 0
}

func (m *DataStorePath) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *DataStorePath) GetIsDefPath() bool {
	if m != nil {
		return m.IsDefPath
	}
	return false
}

func (m *DataStorePath) GetDataPath() string {
	if m != nil {
		return m.DataPath
	}
	return ""
}

type TopicRmvInfo struct {
	TopicName            string   `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	StatusId             int32    `protobuf:"varint,2,opt,name=statusId,proto3" json:"statusId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicRmvInfo) Reset()         { *m = TopicRmvInfo{} }
func (m *TopicRmvInfo) String() string { return proto.CompactTextString(m) }
func (*TopicRmvInfo) ProtoMessage()    {}
func (*TopicRmvInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{7}
}

func (m *TopicRmvInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicRmvInfo.Unmarshal(m, b)
}
func (m *TopicRmvInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicRmvInfo.Marshal(b, m, deterministic)
}
func (m *TopicRmvInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicRmvInfo.Merge(m, src)
}
func (m *TopicRmvInfo) XXX_Size() int {
	return xxx_messageInfo_TopicRmvInfo.Size(m)
}
func (m *TopicRmvInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicRmvInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TopicRmvInfo proto.InternalMessageInfo

func (m *TopicRmvInfo) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *TopicRmvInfo) GetStatusId() int32 {
	if m != nil {
		return m.StatusId
	}
	return 0
}

type DefaultConfigInfo struct {
	NumTopicStores       int32    `protobuf:"varint,1,opt,name=numTopicStores,proto3" json:"numTopicStores,omitempty"`
	NumPartitions        int32    `protobuf:"varint,2,opt,name=numPartitions,proto3" json:"numPartitions,omitempty"`
	UnflushMsgCnt        int32    `protobuf:"varint,3,opt,name=unflushMsgCnt,proto3" json:"unflushMsgCnt,omitempty"`
	UnflushInterval      int32    `protobuf:"varint,4,opt,name=unflushInterval,proto3" json:"unflushInterval,omitempty"`
	UnflushDataSize      int32    `protobuf:"varint,5,opt,name=unflushDataSize,proto3" json:"unflushDataSize,omitempty"`
	MemCacheBlockSize    int32    `protobuf:"varint,6,opt,name=memCacheBlockSize,proto3" json:"memCacheBlockSize,omitempty"`
	NumMemCacheBlock     int32    `protobuf:"varint,7,opt,name=numMemCacheBlock,proto3" json:"numMemCacheBlock,omitempty"`
	BathDiskWriteUnit    int32    `protobuf:"varint,8,opt,name=bathDiskWriteUnit,proto3" json:"bathDiskWriteUnit,omitempty"`
	BathDiskReadUnit     int32    `protobuf:"varint,9,opt,name=bathDiskReadUnit,proto3" json:"bathDiskReadUnit,omitempty"`
	AcceptPublish        bool     `protobuf:"varint,10,opt,name=acceptPublish,proto3" json:"acceptPublish,omitempty"`
	AcceptSubscribe      bool     `protobuf:"varint,11,opt,name=acceptSubscribe,proto3" json:"acceptSubscribe,omitempty"`
	DeletePolicy         string   `protobuf:"bytes,12,opt,name=deletePolicy,proto3" json:"deletePolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultConfigInfo) Reset()         { *m = DefaultConfigInfo{} }
func (m *DefaultConfigInfo) String() string { return proto.CompactTextString(m) }
func (*DefaultConfigInfo) ProtoMessage()    {}
func (*DefaultConfigInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{8}
}

func (m *DefaultConfigInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultConfigInfo.Unmarshal(m, b)
}
func (m *DefaultConfigInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultConfigInfo.Marshal(b, m, deterministic)
}
func (m *DefaultConfigInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultConfigInfo.Merge(m, src)
}
func (m *DefaultConfigInfo) XXX_Size() int {
	return xxx_messageInfo_DefaultConfigInfo.Size(m)
}
func (m *DefaultConfigInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultConfigInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultConfigInfo proto.InternalMessageInfo

func (m *DefaultConfigInfo) GetNumTopicStores() int32 {
	if m != nil {
		return m.NumTopicStores
	}
	return 0
}

func (m *DefaultConfigInfo) GetNumPartitions() int32 {
	if m != nil {
		return m.NumPartitions
	}
	return 0
}

func (m *DefaultConfigInfo) GetUnflushMsgCnt() int32 {
	if m != nil {
		return m.UnflushMsgCnt
	}
	return 0
}

func (m *DefaultConfigInfo) GetUnflushInterval() int32 {
	if m != nil {
		return m.UnflushInterval
	}
	return 0
}

func (m *DefaultConfigInfo) GetUnflushDataSize() int32 {
	if m != nil {
		return m.UnflushDataSize
	}
	return 0
}

func (m *DefaultConfigInfo) GetMemCacheBlockSize() int32 {
	if m != nil {
		return m.MemCacheBlockSize
	}
	return 0
}

func (m *DefaultConfigInfo) GetNumMemCacheBlock() int32 {
	if m != nil {
		return m.NumMemCacheBlock
	}
	return 0
}

func (m *DefaultConfigInfo) GetBathDiskWriteUnit() int32 {
	if m != nil {
		return m.BathDiskWriteUnit
	}
	return 0
}

func (m *DefaultConfigInfo) GetBathDiskReadUnit() int32 {
	if m != nil {
		return m.BathDiskReadUnit
	}
	return 0
}

func (m *DefaultConfigInfo) GetAcceptPublish() bool {
	if m != nil {
		return m.AcceptPublish
	}
	return false
}

func (m *DefaultConfigInfo) GetAcceptSubscribe() bool {
	if m != nil {
		return m.AcceptSubscribe
	}
	return false
}

func (m *DefaultConfigInfo) GetDeletePolicy() string {
	if m != nil {
		return m.DeletePolicy
	}
	return ""
}

type TopicConfigInfo struct {
	TopicName            string           `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	StatusId             int32            `protobuf:"varint,2,opt,name=statusId,proto3" json:"statusId,omitempty"`
	NumTopicStores       int32            `protobuf:"varint,3,opt,name=numTopicStores,proto3" json:"numTopicStores,omitempty"`
	NumPartitions        int32            `protobuf:"varint,4,opt,name=numPartitions,proto3" json:"numPartitions,omitempty"`
	UnflushMsgCnt        int32            `protobuf:"varint,5,opt,name=unflushMsgCnt,proto3" json:"unflushMsgCnt,omitempty"`
	UnflushInterval      int32            `protobuf:"varint,6,opt,name=unflushInterval,proto3" json:"unflushInterval,omitempty"`
	UnflushDataSize      int32            `protobuf:"varint,7,opt,name=unflushDataSize,proto3" json:"unflushDataSize,omitempty"`
	MemCacheBlockSize    int32            `protobuf:"varint,8,opt,name=memCacheBlockSize,proto3" json:"memCacheBlockSize,omitempty"`
	NumMemCacheBlock     int32            `protobuf:"varint,9,opt,name=numMemCacheBlock,proto3" json:"numMemCacheBlock,omitempty"`
	AcceptPublish        bool             `protobuf:"varint,10,opt,name=acceptPublish,proto3" json:"acceptPublish,omitempty"`
	AcceptSubscribe      bool             `protobuf:"varint,11,opt,name=acceptSubscribe,proto3" json:"acceptSubscribe,omitempty"`
	DeletePolicy         string           `protobuf:"bytes,12,opt,name=deletePolicy,proto3" json:"deletePolicy,omitempty"`
	DataPath             []*DataStorePath `protobuf:"bytes,13,rep,name=dataPath,proto3" json:"dataPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TopicConfigInfo) Reset()         { *m = TopicConfigInfo{} }
func (m *TopicConfigInfo) String() string { return proto.CompactTextString(m) }
func (*TopicConfigInfo) ProtoMessage()    {}
func (*TopicConfigInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{9}
}

func (m *TopicConfigInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicConfigInfo.Unmarshal(m, b)
}
func (m *TopicConfigInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicConfigInfo.Marshal(b, m, deterministic)
}
func (m *TopicConfigInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicConfigInfo.Merge(m, src)
}
func (m *TopicConfigInfo) XXX_Size() int {
	return xxx_messageInfo_TopicConfigInfo.Size(m)
}
func (m *TopicConfigInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicConfigInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TopicConfigInfo proto.InternalMessageInfo

func (m *TopicConfigInfo) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *TopicConfigInfo) GetStatusId() int32 {
	if m != nil {
		return m.StatusId
	}
	return 0
}

func (m *TopicConfigInfo) GetNumTopicStores() int32 {
	if m != nil {
		return m.NumTopicStores
	}
	return 0
}

func (m *TopicConfigInfo) GetNumPartitions() int32 {
	if m != nil {
		return m.NumPartitions
	}
	return 0
}

func (m *TopicConfigInfo) GetUnflushMsgCnt() int32 {
	if m != nil {
		return m.UnflushMsgCnt
	}
	return 0
}

func (m *TopicConfigInfo) GetUnflushInterval() int32 {
	if m != nil {
		return m.UnflushInterval
	}
	return 0
}

func (m *TopicConfigInfo) GetUnflushDataSize() int32 {
	if m != nil {
		return m.UnflushDataSize
	}
	return 0
}

func (m *TopicConfigInfo) GetMemCacheBlockSize() int32 {
	if m != nil {
		return m.MemCacheBlockSize
	}
	return 0
}

func (m *TopicConfigInfo) GetNumMemCacheBlock() int32 {
	if m != nil {
		return m.NumMemCacheBlock
	}
	return 0
}

func (m *TopicConfigInfo) GetAcceptPublish() bool {
	if m != nil {
		return m.AcceptPublish
	}
	return false
}

func (m *TopicConfigInfo) GetAcceptSubscribe() bool {
	if m != nil {
		return m.AcceptSubscribe
	}
	return false
}

func (m *TopicConfigInfo) GetDeletePolicy() string {
	if m != nil {
		return m.DeletePolicy
	}
	return ""
}

func (m *TopicConfigInfo) GetDataPath() []*DataStorePath {
	if m != nil {
		return m.DataPath
	}
	return nil
}

type BrokerConfigInfo struct {
	BrokerConfId         int64              `protobuf:"varint,1,opt,name=brokerConfId,proto3" json:"brokerConfId,omitempty"`
	ConfCheckSumId       int32              `protobuf:"varint,2,opt,name=confCheckSumId,proto3" json:"confCheckSumId,omitempty"`
	DefConfigInfo        *DefaultConfigInfo `protobuf:"bytes,3,opt,name=defConfigInfo,proto3" json:"defConfigInfo,omitempty"`
	TopicConfigInfos     []*TopicConfigInfo `protobuf:"bytes,4,rep,name=topicConfigInfos,proto3" json:"topicConfigInfos,omitempty"`
	EnableTls            bool               `protobuf:"varint,5,opt,name=enableTls,proto3" json:"enableTls,omitempty"`
	TlsPort              int32              `protobuf:"varint,6,opt,name=tlsPort,proto3" json:"tlsPort,omitempty"`
	WebPort              int32              `protobuf:"varint,7,opt,name=webPort,proto3" json:"webPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BrokerConfigInfo) Reset()         { *m = BrokerConfigInfo{} }
func (m *BrokerConfigInfo) String() string { return proto.CompactTextString(m) }
func (*BrokerConfigInfo) ProtoMessage()    {}
func (*BrokerConfigInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{10}
}

func (m *BrokerConfigInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerConfigInfo.Unmarshal(m, b)
}
func (m *BrokerConfigInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerConfigInfo.Marshal(b, m, deterministic)
}
func (m *BrokerConfigInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerConfigInfo.Merge(m, src)
}
func (m *BrokerConfigInfo) XXX_Size() int {
	return xxx_messageInfo_BrokerConfigInfo.Size(m)
}
func (m *BrokerConfigInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerConfigInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerConfigInfo proto.InternalMessageInfo

func (m *BrokerConfigInfo) GetBrokerConfId() int64 {
	if m != nil {
		return m.BrokerConfId
	}
	return 0
}

func (m *BrokerConfigInfo) GetConfCheckSumId() int32 {
	if m != nil {
		return m.ConfCheckSumId
	}
	return 0
}

func (m *BrokerConfigInfo) GetDefConfigInfo() *DefaultConfigInfo {
	if m != nil {
		return m.DefConfigInfo
	}
	return nil
}

func (m *BrokerConfigInfo) GetTopicConfigInfos() []*TopicConfigInfo {
	if m != nil {
		return m.TopicConfigInfos
	}
	return nil
}

func (m *BrokerConfigInfo) GetEnableTls() bool {
	if m != nil {
		return m.EnableTls
	}
	return false
}

func (m *BrokerConfigInfo) GetTlsPort() int32 {
	if m != nil {
		return m.TlsPort
	}
	return 0
}

func (m *BrokerConfigInfo) GetWebPort() int32 {
	if m != nil {
		return m.WebPort
	}
	return 0
}

type BrokerPolicyInfo struct {
	PolicyId             int64    `protobuf:"varint,1,opt,name=policyId,proto3" json:"policyId,omitempty"`
	QryPriorityId        int32    `protobuf:"varint,2,opt,name=qryPriorityId,proto3" json:"qryPriorityId,omitempty"`
	PolicyInfo           string   `protobuf:"bytes,3,opt,name=policyInfo,proto3" json:"policyInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerPolicyInfo) Reset()         { *m = BrokerPolicyInfo{} }
func (m *BrokerPolicyInfo) String() string { return proto.CompactTextString(m) }
func (*BrokerPolicyInfo) ProtoMessage()    {}
func (*BrokerPolicyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{11}
}

func (m *BrokerPolicyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerPolicyInfo.Unmarshal(m, b)
}
func (m *BrokerPolicyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerPolicyInfo.Marshal(b, m, deterministic)
}
func (m *BrokerPolicyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerPolicyInfo.Merge(m, src)
}
func (m *BrokerPolicyInfo) XXX_Size() int {
	return xxx_messageInfo_BrokerPolicyInfo.Size(m)
}
func (m *BrokerPolicyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerPolicyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerPolicyInfo proto.InternalMessageInfo

func (m *BrokerPolicyInfo) GetPolicyId() int64 {
	if m != nil {
		return m.PolicyId
	}
	return 0
}

func (m *BrokerPolicyInfo) GetQryPriorityId() int32 {
	if m != nil {
		return m.QryPriorityId
	}
	return 0
}

func (m *BrokerPolicyInfo) GetPolicyInfo() string {
	if m != nil {
		return m.PolicyInfo
	}
	return ""
}

type BrokerStatusInfo struct {
	IsOnline             bool     `protobuf:"varint,1,opt,name=isOnline,proto3" json:"isOnline,omitempty"`
	ReadStatusRpt        int32    `protobuf:"varint,2,opt,name=readStatusRpt,proto3" json:"readStatusRpt,omitempty"`
	WriteStatusRpt       int32    `protobuf:"varint,3,opt,name=writeStatusRpt,proto3" json:"writeStatusRpt,omitempty"`
	LastOperateId        int32    `protobuf:"varint,4,opt,name=lastOperateId,proto3" json:"lastOperateId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BrokerStatusInfo) Reset()         { *m = BrokerStatusInfo{} }
func (m *BrokerStatusInfo) String() string { return proto.CompactTextString(m) }
func (*BrokerStatusInfo) ProtoMessage()    {}
func (*BrokerStatusInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{12}
}

func (m *BrokerStatusInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerStatusInfo.Unmarshal(m, b)
}
func (m *BrokerStatusInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerStatusInfo.Marshal(b, m, deterministic)
}
func (m *BrokerStatusInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerStatusInfo.Merge(m, src)
}
func (m *BrokerStatusInfo) XXX_Size() int {
	return xxx_messageInfo_BrokerStatusInfo.Size(m)
}
func (m *BrokerStatusInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerStatusInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerStatusInfo proto.InternalMessageInfo

func (m *BrokerStatusInfo) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *BrokerStatusInfo) GetReadStatusRpt() int32 {
	if m != nil {
		return m.ReadStatusRpt
	}
	return 0
}

func (m *BrokerStatusInfo) GetWriteStatusRpt() int32 {
	if m != nil {
		return m.WriteStatusRpt
	}
	return 0
}

func (m *BrokerStatusInfo) GetLastOperateId() int32 {
	if m != nil {
		return m.LastOperateId
	}
	return 0
}

type BrokerOperateInfo struct {
	OperateId int32 `protobuf:"varint,1,opt,name=operateId,proto3" json:"operateId,omitempty"`
	// 00:normal, 01:stop read, 10:stop write, 11:stop read and write
	FrcServiceStatus          int32           `protobuf:"varint,2,opt,name=frcServiceStatus,proto3" json:"frcServiceStatus,omitempty"`
	FrcRptConfig              bool            `protobuf:"varint,3,opt,name=frcRptConfig,proto3" json:"frcRptConfig,omitempty"`
	EnableConsumeAuthenticate bool            `protobuf:"varint,4,opt,name=enableConsumeAuthenticate,proto3" json:"enableConsumeAuthenticate,omitempty"`
	EnableConsumeAuthorize    bool            `protobuf:"varint,5,opt,name=enableConsumeAuthorize,proto3" json:"enableConsumeAuthorize,omitempty"`
	EnableProduceAuthenticate bool            `protobuf:"varint,6,opt,name=enableProduceAuthenticate,proto3" json:"enableProduceAuthenticate,omitempty"`
	EnableProduceAuthorize    bool            `protobuf:"varint,7,opt,name=enableProduceAuthorize,proto3" json:"enableProduceAuthorize,omitempty"`
	EnableVisitTokenCheck     bool            `protobuf:"varint,8,opt,name=enableVisitTokenCheck,proto3" json:"enableVisitTokenCheck,omitempty"`
	RmvTopicsInfo             []*TopicRmvInfo `protobuf:"bytes,9,rep,name=rmvTopicsInfo,proto3" json:"rmvTopicsInfo,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}        `json:"-"`
	XXX_unrecognized          []byte          `json:"-"`
	XXX_sizecache             int32           `json:"-"`
}

func (m *BrokerOperateInfo) Reset()         { *m = BrokerOperateInfo{} }
func (m *BrokerOperateInfo) String() string { return proto.CompactTextString(m) }
func (*BrokerOperateInfo) ProtoMessage()    {}
func (*BrokerOperateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{13}
}

func (m *BrokerOperateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BrokerOperateInfo.Unmarshal(m, b)
}
func (m *BrokerOperateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BrokerOperateInfo.Marshal(b, m, deterministic)
}
func (m *BrokerOperateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BrokerOperateInfo.Merge(m, src)
}
func (m *BrokerOperateInfo) XXX_Size() int {
	return xxx_messageInfo_BrokerOperateInfo.Size(m)
}
func (m *BrokerOperateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BrokerOperateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BrokerOperateInfo proto.InternalMessageInfo

func (m *BrokerOperateInfo) GetOperateId() int32 {
	if m != nil {
		return m.OperateId
	}
	return 0
}

func (m *BrokerOperateInfo) GetFrcServiceStatus() int32 {
	if m != nil {
		return m.FrcServiceStatus
	}
	return 0
}

func (m *BrokerOperateInfo) GetFrcRptConfig() bool {
	if m != nil {
		return m.FrcRptConfig
	}
	return false
}

func (m *BrokerOperateInfo) GetEnableConsumeAuthenticate() bool {
	if m != nil {
		return m.EnableConsumeAuthenticate
	}
	return false
}

func (m *BrokerOperateInfo) GetEnableConsumeAuthorize() bool {
	if m != nil {
		return m.EnableConsumeAuthorize
	}
	return false
}

func (m *BrokerOperateInfo) GetEnableProduceAuthenticate() bool {
	if m != nil {
		return m.EnableProduceAuthenticate
	}
	return false
}

func (m *BrokerOperateInfo) GetEnableProduceAuthorize() bool {
	if m != nil {
		return m.EnableProduceAuthorize
	}
	return false
}

func (m *BrokerOperateInfo) GetEnableVisitTokenCheck() bool {
	if m != nil {
		return m.EnableVisitTokenCheck
	}
	return false
}

func (m *BrokerOperateInfo) GetRmvTopicsInfo() []*TopicRmvInfo {
	if m != nil {
		return m.RmvTopicsInfo
	}
	return nil
}

type RegisterRequestB2M struct {
	ClientId             string                 `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	StatusRptInfo        *BrokerStatusInfo      `protobuf:"bytes,2,opt,name=statusRptInfo,proto3" json:"statusRptInfo,omitempty"`
	ConfigInfo           *BrokerConfigInfo      `protobuf:"bytes,3,opt,name=configInfo,proto3" json:"configInfo,omitempty"`
	PolicyInfo           *BrokerPolicyInfo      `protobuf:"bytes,4,opt,name=policyInfo,proto3" json:"policyInfo,omitempty"`
	AuthInfo             *MasterCertificateInfo `protobuf:"bytes,5,opt,name=authInfo,proto3" json:"authInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RegisterRequestB2M) Reset()         { *m = RegisterRequestB2M{} }
func (m *RegisterRequestB2M) String() string { return proto.CompactTextString(m) }
func (*RegisterRequestB2M) ProtoMessage()    {}
func (*RegisterRequestB2M) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{14}
}

func (m *RegisterRequestB2M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequestB2M.Unmarshal(m, b)
}
func (m *RegisterRequestB2M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequestB2M.Marshal(b, m, deterministic)
}
func (m *RegisterRequestB2M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequestB2M.Merge(m, src)
}
func (m *RegisterRequestB2M) XXX_Size() int {
	return xxx_messageInfo_RegisterRequestB2M.Size(m)
}
func (m *RegisterRequestB2M) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequestB2M.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequestB2M proto.InternalMessageInfo

func (m *RegisterRequestB2M) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *RegisterRequestB2M) GetStatusRptInfo() *BrokerStatusInfo {
	if m != nil {
		return m.StatusRptInfo
	}
	return nil
}

func (m *RegisterRequestB2M) GetConfigInfo() *BrokerConfigInfo {
	if m != nil {
		return m.ConfigInfo
	}
	return nil
}

func (m *RegisterRequestB2M) GetPolicyInfo() *BrokerPolicyInfo {
	if m != nil {
		return m.PolicyInfo
	}
	return nil
}

func (m *RegisterRequestB2M) GetAuthInfo() *MasterCertificateInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

type RegisterResponseM2B struct {
	ErrCode              int32                       `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string                      `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	ConfigInfo           *BrokerConfigInfo           `protobuf:"bytes,3,opt,name=configInfo,proto3" json:"configInfo,omitempty"`
	OperateInfo          *BrokerOperateInfo          `protobuf:"bytes,4,opt,name=operateInfo,proto3" json:"operateInfo,omitempty"`
	PolicyInfo           *BrokerPolicyInfo           `protobuf:"bytes,5,opt,name=policyInfo,proto3" json:"policyInfo,omitempty"`
	AuthorizedInfo       *MasterBrokerAuthorizedInfo `protobuf:"bytes,6,opt,name=authorizedInfo,proto3" json:"authorizedInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *RegisterResponseM2B) Reset()         { *m = RegisterResponseM2B{} }
func (m *RegisterResponseM2B) String() string { return proto.CompactTextString(m) }
func (*RegisterResponseM2B) ProtoMessage()    {}
func (*RegisterResponseM2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{15}
}

func (m *RegisterResponseM2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponseM2B.Unmarshal(m, b)
}
func (m *RegisterResponseM2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponseM2B.Marshal(b, m, deterministic)
}
func (m *RegisterResponseM2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponseM2B.Merge(m, src)
}
func (m *RegisterResponseM2B) XXX_Size() int {
	return xxx_messageInfo_RegisterResponseM2B.Size(m)
}
func (m *RegisterResponseM2B) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponseM2B.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponseM2B proto.InternalMessageInfo

func (m *RegisterResponseM2B) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *RegisterResponseM2B) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *RegisterResponseM2B) GetConfigInfo() *BrokerConfigInfo {
	if m != nil {
		return m.ConfigInfo
	}
	return nil
}

func (m *RegisterResponseM2B) GetOperateInfo() *BrokerOperateInfo {
	if m != nil {
		return m.OperateInfo
	}
	return nil
}

func (m *RegisterResponseM2B) GetPolicyInfo() *BrokerPolicyInfo {
	if m != nil {
		return m.PolicyInfo
	}
	return nil
}

func (m *RegisterResponseM2B) GetAuthorizedInfo() *MasterBrokerAuthorizedInfo {
	if m != nil {
		return m.AuthorizedInfo
	}
	return nil
}

type HeartRequestB2M struct {
	BrokerId             string                 `protobuf:"bytes,1,opt,name=brokerId,proto3" json:"brokerId,omitempty"`
	StatusRptInfo        *BrokerStatusInfo      `protobuf:"bytes,2,opt,name=statusRptInfo,proto3" json:"statusRptInfo,omitempty"`
	ConfigInfo           *BrokerConfigInfo      `protobuf:"bytes,3,opt,name=configInfo,proto3" json:"configInfo,omitempty"`
	PolicyInfo           *BrokerPolicyInfo      `protobuf:"bytes,4,opt,name=policyInfo,proto3" json:"policyInfo,omitempty"`
	AuthInfo             *MasterCertificateInfo `protobuf:"bytes,5,opt,name=authInfo,proto3" json:"authInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *HeartRequestB2M) Reset()         { *m = HeartRequestB2M{} }
func (m *HeartRequestB2M) String() string { return proto.CompactTextString(m) }
func (*HeartRequestB2M) ProtoMessage()    {}
func (*HeartRequestB2M) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{16}
}

func (m *HeartRequestB2M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartRequestB2M.Unmarshal(m, b)
}
func (m *HeartRequestB2M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartRequestB2M.Marshal(b, m, deterministic)
}
func (m *HeartRequestB2M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartRequestB2M.Merge(m, src)
}
func (m *HeartRequestB2M) XXX_Size() int {
	return xxx_messageInfo_HeartRequestB2M.Size(m)
}
func (m *HeartRequestB2M) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartRequestB2M.DiscardUnknown(m)
}

var xxx_messageInfo_HeartRequestB2M proto.InternalMessageInfo

func (m *HeartRequestB2M) GetBrokerId() string {
	if m != nil {
		return m.BrokerId
	}
	return ""
}

func (m *HeartRequestB2M) GetStatusRptInfo() *BrokerStatusInfo {
	if m != nil {
		return m.StatusRptInfo
	}
	return nil
}

func (m *HeartRequestB2M) GetConfigInfo() *BrokerConfigInfo {
	if m != nil {
		return m.ConfigInfo
	}
	return nil
}

func (m *HeartRequestB2M) GetPolicyInfo() *BrokerPolicyInfo {
	if m != nil {
		return m.PolicyInfo
	}
	return nil
}

func (m *HeartRequestB2M) GetAuthInfo() *MasterCertificateInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

type HeartResponseM2B struct {
	ErrCode              int32                       `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string                      `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	ConfigInfo           *BrokerConfigInfo           `protobuf:"bytes,3,opt,name=configInfo,proto3" json:"configInfo,omitempty"`
	OperateInfo          *BrokerOperateInfo          `protobuf:"bytes,4,opt,name=operateInfo,proto3" json:"operateInfo,omitempty"`
	PolicyInfo           *BrokerPolicyInfo           `protobuf:"bytes,5,opt,name=policyInfo,proto3" json:"policyInfo,omitempty"`
	BrokerAuthorizedInfo *MasterBrokerAuthorizedInfo `protobuf:"bytes,6,opt,name=brokerAuthorizedInfo,proto3" json:"brokerAuthorizedInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *HeartResponseM2B) Reset()         { *m = HeartResponseM2B{} }
func (m *HeartResponseM2B) String() string { return proto.CompactTextString(m) }
func (*HeartResponseM2B) ProtoMessage()    {}
func (*HeartResponseM2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{17}
}

func (m *HeartResponseM2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartResponseM2B.Unmarshal(m, b)
}
func (m *HeartResponseM2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartResponseM2B.Marshal(b, m, deterministic)
}
func (m *HeartResponseM2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartResponseM2B.Merge(m, src)
}
func (m *HeartResponseM2B) XXX_Size() int {
	return xxx_messageInfo_HeartResponseM2B.Size(m)
}
func (m *HeartResponseM2B) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartResponseM2B.DiscardUnknown(m)
}

var xxx_messageInfo_HeartResponseM2B proto.InternalMessageInfo

func (m *HeartResponseM2B) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *HeartResponseM2B) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *HeartResponseM2B) GetConfigInfo() *BrokerConfigInfo {
	if m != nil {
		return m.ConfigInfo
	}
	return nil
}

func (m *HeartResponseM2B) GetOperateInfo() *BrokerOperateInfo {
	if m != nil {
		return m.OperateInfo
	}
	return nil
}

func (m *HeartResponseM2B) GetPolicyInfo() *BrokerPolicyInfo {
	if m != nil {
		return m.PolicyInfo
	}
	return nil
}

func (m *HeartResponseM2B) GetBrokerAuthorizedInfo() *MasterBrokerAuthorizedInfo {
	if m != nil {
		return m.BrokerAuthorizedInfo
	}
	return nil
}

type CloseRequestB2M struct {
	BrokerId             string                 `protobuf:"bytes,1,opt,name=brokerId,proto3" json:"brokerId,omitempty"`
	AuthInfo             *MasterCertificateInfo `protobuf:"bytes,2,opt,name=authInfo,proto3" json:"authInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CloseRequestB2M) Reset()         { *m = CloseRequestB2M{} }
func (m *CloseRequestB2M) String() string { return proto.CompactTextString(m) }
func (*CloseRequestB2M) ProtoMessage()    {}
func (*CloseRequestB2M) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{18}
}

func (m *CloseRequestB2M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRequestB2M.Unmarshal(m, b)
}
func (m *CloseRequestB2M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRequestB2M.Marshal(b, m, deterministic)
}
func (m *CloseRequestB2M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRequestB2M.Merge(m, src)
}
func (m *CloseRequestB2M) XXX_Size() int {
	return xxx_messageInfo_CloseRequestB2M.Size(m)
}
func (m *CloseRequestB2M) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRequestB2M.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRequestB2M proto.InternalMessageInfo

func (m *CloseRequestB2M) GetBrokerId() string {
	if m != nil {
		return m.BrokerId
	}
	return ""
}

func (m *CloseRequestB2M) GetAuthInfo() *MasterCertificateInfo {
	if m != nil {
		return m.AuthInfo
	}
	return nil
}

type CloseResponseM2B struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseResponseM2B) Reset()         { *m = CloseResponseM2B{} }
func (m *CloseResponseM2B) String() string { return proto.CompactTextString(m) }
func (*CloseResponseM2B) ProtoMessage()    {}
func (*CloseResponseM2B) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{19}
}

func (m *CloseResponseM2B) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseResponseM2B.Unmarshal(m, b)
}
func (m *CloseResponseM2B) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseResponseM2B.Marshal(b, m, deterministic)
}
func (m *CloseResponseM2B) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseResponseM2B.Merge(m, src)
}
func (m *CloseResponseM2B) XXX_Size() int {
	return xxx_messageInfo_CloseResponseM2B.Size(m)
}
func (m *CloseResponseM2B) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseResponseM2B.DiscardUnknown(m)
}

var xxx_messageInfo_CloseResponseM2B proto.InternalMessageInfo

func (m *CloseResponseM2B) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CloseResponseM2B) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*EventProto)(nil), "protocol.EventProto")
	proto.RegisterType((*EnableBrokerFunInfo)(nil), "protocol.EnableBrokerFunInfo")
	proto.RegisterType((*AuthenticateInfo)(nil), "protocol.AuthenticateInfo")
	proto.RegisterType((*MasterCertificateInfo)(nil), "protocol.MasterCertificateInfo")
	proto.RegisterType((*MasterAuthorizedInfo)(nil), "protocol.MasterAuthorizedInfo")
	proto.RegisterType((*MasterBrokerAuthorizedInfo)(nil), "protocol.MasterBrokerAuthorizedInfo")
	proto.RegisterType((*DataStorePath)(nil), "protocol.DataStorePath")
	proto.RegisterType((*TopicRmvInfo)(nil), "protocol.TopicRmvInfo")
	proto.RegisterType((*DefaultConfigInfo)(nil), "protocol.DefaultConfigInfo")
	proto.RegisterType((*TopicConfigInfo)(nil), "protocol.TopicConfigInfo")
	proto.RegisterType((*BrokerConfigInfo)(nil), "protocol.BrokerConfigInfo")
	proto.RegisterType((*BrokerPolicyInfo)(nil), "protocol.BrokerPolicyInfo")
	proto.RegisterType((*BrokerStatusInfo)(nil), "protocol.BrokerStatusInfo")
	proto.RegisterType((*BrokerOperateInfo)(nil), "protocol.BrokerOperateInfo")
	proto.RegisterType((*RegisterRequestB2M)(nil), "protocol.RegisterRequestB2M")
	proto.RegisterType((*RegisterResponseM2B)(nil), "protocol.RegisterResponseM2B")
	proto.RegisterType((*HeartRequestB2M)(nil), "protocol.HeartRequestB2M")
	proto.RegisterType((*HeartResponseM2B)(nil), "protocol.HeartResponseM2B")
	proto.RegisterType((*CloseRequestB2M)(nil), "protocol.CloseRequestB2M")
	proto.RegisterType((*CloseResponseM2B)(nil), "protocol.CloseResponseM2B")
}

func init() { proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705) }

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 1359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x57, 0x5b, 0x6f, 0x1b, 0x45,
	0x14, 0x96, 0x6f, 0x89, 0x7d, 0x9c, 0x34, 0xe9, 0x36, 0x2d, 0x6e, 0x8b, 0x20, 0x5a, 0x55, 0x28,
	0x42, 0x34, 0xad, 0x5c, 0xd4, 0x07, 0x28, 0x12, 0x89, 0x53, 0xd4, 0x48, 0x84, 0x5a, 0x93, 0x70,
	0x11, 0x6f, 0xe3, 0xdd, 0xb1, 0x3d, 0x64, 0x77, 0xc6, 0x9d, 0x99, 0x75, 0x15, 0xc4, 0x0b, 0x97,
	0xdf, 0xc0, 0x23, 0x0f, 0x08, 0x89, 0x9f, 0x80, 0xc4, 0x6f, 0xe0, 0x95, 0x1f, 0xc0, 0x3f, 0x41,
	0x73, 0xd9, 0xab, 0xdd, 0x2a, 0x49, 0x91, 0x78, 0xe8, 0x53, 0x72, 0xbe, 0x73, 0x9b, 0x39, 0xf3,
	0x9d, 0xb3, 0xc7, 0xb0, 0x16, 0x63, 0xa9, 0x88, 0xd8, 0x9d, 0x09, 0xae, 0xb8, 0xd7, 0x36, 0x7f,
	0x02, 0x1e, 0xf9, 0x3f, 0xd5, 0x00, 0x1e, 0xcf, 0x09, 0x53, 0x43, 0xa3, 0xd8, 0x86, 0xae, 0x20,
	0x23, 0x1c, 0x61, 0x16, 0x90, 0xc3, 0xb0, 0x57, 0xdb, 0xae, 0xed, 0x34, 0x50, 0x11, 0xf2, 0x6e,
	0xc0, 0x0a, 0x9f, 0x9d, 0x9c, 0xcd, 0x48, 0xaf, 0xbe, 0x5d, 0xdb, 0x69, 0x21, 0x27, 0x69, 0x5c,
	0x2a, 0xac, 0x12, 0xd9, 0x6b, 0x58, 0xdc, 0x4a, 0xde, 0x1d, 0x58, 0x97, 0xc9, 0x48, 0x06, 0x82,
	0x8e, 0xc8, 0x21, 0x1b, 0xf3, 0x5e, 0x73, 0xbb, 0xb1, 0xd3, 0x41, 0x65, 0xd0, 0xff, 0xa3, 0x0e,
	0xd7, 0x1e, 0x33, 0x3c, 0x8a, 0xc8, 0xbe, 0xe0, 0xa7, 0x44, 0x7c, 0x92, 0x30, 0x8d, 0x7b, 0x8f,
	0xe0, 0x26, 0x31, 0xf0, 0x80, 0x33, 0x99, 0xc4, 0x64, 0x2f, 0x51, 0x53, 0xc2, 0x14, 0x0d, 0xb0,
	0x22, 0xe6, 0x74, 0x6d, 0xf4, 0x62, 0x03, 0xef, 0x21, 0xdc, 0x58, 0x50, 0x72, 0x41, 0xbf, 0xb5,
	0x67, 0x6f, 0xa3, 0x17, 0x68, 0xf3, 0xac, 0x43, 0xc1, 0xc3, 0x24, 0x28, 0x67, 0x6d, 0x14, 0xb3,
	0x2e, 0x31, 0xc8, 0xb3, 0x16, 0x94, 0x36, 0x6b, 0xb3, 0x98, 0xb5, 0xaa, 0xf5, 0xde, 0x87, 0xeb,
	0x56, 0xf3, 0x05, 0x95, 0x54, 0x9d, 0xf0, 0x53, 0xc2, 0x06, 0x53, 0x12, 0x9c, 0xf6, 0x5a, 0xc6,
	0x6d, 0xb9, 0xd2, 0xff, 0xa5, 0x06, 0x9b, 0xc5, 0xf4, 0xa6, 0x6c, 0xb7, 0xa0, 0x9d, 0x48, 0x22,
	0x3e, 0xc3, 0xb1, 0xad, 0x52, 0x07, 0x65, 0xb2, 0xf7, 0x26, 0x74, 0x14, 0x8d, 0x89, 0x54, 0x38,
	0x9e, 0x99, 0x3a, 0x34, 0x50, 0x0e, 0x78, 0x5b, 0xd0, 0x62, 0x9c, 0x05, 0xc4, 0xbd, 0xa2, 0x15,
	0xb4, 0x0f, 0x57, 0xd3, 0x21, 0x16, 0x38, 0x96, 0xe6, 0x16, 0x1d, 0x94, 0x03, 0x5a, 0x2b, 0xe9,
	0x84, 0x61, 0x95, 0x08, 0x62, 0x0e, 0xdb, 0x41, 0x39, 0xe0, 0x9f, 0xc1, 0xf5, 0x23, 0xc3, 0xbd,
	0x01, 0x11, 0x8a, 0x8e, 0xf3, 0x43, 0x3e, 0x84, 0x36, 0x4e, 0xd4, 0xd4, 0x90, 0x42, 0x1f, 0xb2,
	0xdb, 0xbf, 0xb5, 0x9b, 0xf2, 0x72, 0xb7, 0x7a, 0x25, 0x94, 0xd9, 0x7a, 0x3b, 0xb0, 0x81, 0xd3,
	0xa2, 0x85, 0xa6, 0x12, 0xe6, 0x1a, 0x1d, 0x54, 0x85, 0xfd, 0xef, 0x60, 0xcb, 0xa6, 0xce, 0x8a,
	0x1c, 0x9a, 0x08, 0x7d, 0xd8, 0x9a, 0xeb, 0x32, 0xee, 0x55, 0xc2, 0x58, 0xba, 0x2f, 0xd5, 0x79,
	0xf7, 0xe1, 0x9a, 0x0e, 0xbf, 0xb7, 0x34, 0xf3, 0x32, 0x95, 0xff, 0x43, 0x0d, 0x6e, 0xd9, 0xf4,
	0x96, 0xd3, 0x17, 0x38, 0x44, 0xe7, 0x3f, 0x3b, 0xc4, 0xf7, 0x35, 0x58, 0x3f, 0xc0, 0x0a, 0x1f,
	0x2b, 0x2e, 0xc8, 0x10, 0xab, 0xa9, 0xe6, 0x86, 0x20, 0x01, 0x17, 0xa1, 0xeb, 0xef, 0x16, 0xca,
	0x64, 0xad, 0xa3, 0x72, 0x2f, 0x50, 0x74, 0x9e, 0xb6, 0x48, 0x26, 0xeb, 0x57, 0xa6, 0xf2, 0x80,
	0x8c, 0x75, 0x10, 0xd7, 0x04, 0x39, 0xa0, 0x3d, 0x43, 0xac, 0xb0, 0x51, 0x5a, 0x82, 0x64, 0xb2,
	0xff, 0x04, 0xd6, 0x4e, 0xf8, 0x8c, 0x06, 0x28, 0x9e, 0x9b, 0x9b, 0x6b, 0x06, 0x6a, 0xb9, 0x40,
	0xcf, 0x1c, 0xd0, 0x91, 0xec, 0xe8, 0x38, 0x0c, 0xdd, 0x88, 0xc9, 0x64, 0xff, 0xc7, 0x26, 0x5c,
	0x3d, 0x20, 0x63, 0x9c, 0x44, 0x6a, 0xc0, 0xd9, 0x98, 0x4e, 0x4c, 0xbc, 0x77, 0xe0, 0x0a, 0x4b,
	0x62, 0x93, 0xc2, 0x5c, 0x53, 0xba, 0x7b, 0x55, 0x50, 0x3d, 0x8a, 0x58, 0x12, 0x0f, 0xb1, 0x50,
	0x54, 0x51, 0xce, 0xa4, 0x0b, 0x5f, 0x06, 0xb5, 0x55, 0xc2, 0xc6, 0x51, 0x22, 0xa7, 0x47, 0x72,
	0x32, 0x60, 0xca, 0x75, 0x42, 0x19, 0xd4, 0x24, 0x74, 0xc0, 0x21, 0x53, 0x44, 0xcc, 0x71, 0x64,
	0xae, 0xdd, 0x42, 0x55, 0xb8, 0x60, 0x69, 0xde, 0x41, 0xcf, 0x81, 0x56, 0xc9, 0x32, 0x85, 0xbd,
	0xf7, 0xe0, 0x6a, 0x4c, 0xe2, 0x01, 0x0e, 0xa6, 0x64, 0x3f, 0xe2, 0xc1, 0xa9, 0xb1, 0x5d, 0x31,
	0xb6, 0x8b, 0x0a, 0xef, 0x5d, 0xd8, 0x64, 0x49, 0x7c, 0x54, 0xc4, 0x7b, 0xab, 0xc6, 0x78, 0x01,
	0xd7, 0x91, 0x47, 0x58, 0x4d, 0x0f, 0xa8, 0x3c, 0xfd, 0x52, 0x50, 0x45, 0x3e, 0x67, 0x54, 0xf5,
	0xda, 0x36, 0xf2, 0x82, 0x42, 0x47, 0x4e, 0x41, 0x44, 0x70, 0x68, 0x8c, 0x3b, 0x36, 0x72, 0x15,
	0xd7, 0xd5, 0xc2, 0x41, 0x40, 0x66, 0x6a, 0x98, 0x8c, 0x22, 0x2a, 0xa7, 0x3d, 0x30, 0xcc, 0x28,
	0x83, 0xa6, 0x65, 0x0d, 0x70, 0x9c, 0x4e, 0xfd, 0x5e, 0xd7, 0xd8, 0x55, 0x61, 0xcf, 0x87, 0xb5,
	0x90, 0x44, 0x44, 0x91, 0x21, 0x8f, 0x68, 0x70, 0xd6, 0x5b, 0x33, 0xf4, 0x28, 0x61, 0xfe, 0xcf,
	0x4d, 0xd8, 0x30, 0xef, 0x5a, 0xe0, 0xc0, 0xa5, 0x39, 0xb5, 0x84, 0x3d, 0x8d, 0xf3, 0xb1, 0xa7,
	0x79, 0x2e, 0xf6, 0xb4, 0xce, 0xc9, 0x9e, 0x95, 0x73, 0xb3, 0x67, 0xf5, 0x02, 0xec, 0x69, 0x5f,
	0x84, 0x3d, 0x9d, 0x17, 0xb0, 0xe7, 0x7f, 0x78, 0x63, 0xef, 0x41, 0x61, 0x9e, 0xac, 0x6f, 0x37,
	0x76, 0xba, 0xfd, 0x37, 0xf2, 0x8f, 0x43, 0x69, 0xa0, 0x15, 0x06, 0xcd, 0x9f, 0x75, 0xd8, 0xb4,
	0xb3, 0xb6, 0xc0, 0x0c, 0x1f, 0xd6, 0x46, 0x19, 0x96, 0xed, 0x34, 0x25, 0x4c, 0x73, 0x20, 0xe0,
	0x6c, 0x6c, 0xbe, 0xa8, 0xc7, 0x49, 0x9c, 0xb1, 0xa4, 0x82, 0x7a, 0x7b, 0xb0, 0x1e, 0x92, 0x71,
	0x1e, 0xdc, 0x50, 0xa5, 0xdb, 0xbf, 0x5d, 0x38, 0x5a, 0x75, 0x3a, 0xa1, 0xb2, 0x87, 0xf7, 0x18,
	0x36, 0x55, 0x99, 0xbb, 0xd2, 0xac, 0x44, 0xdd, 0xfe, 0xcd, 0x3c, 0x4a, 0x85, 0xdd, 0x68, 0xc1,
	0x45, 0xf3, 0xdd, 0xee, 0x03, 0x27, 0x91, 0x74, 0x0b, 0x42, 0x0e, 0x78, 0x3d, 0x58, 0x55, 0x91,
	0x1c, 0x72, 0xa1, 0x1c, 0xaf, 0x52, 0x51, 0x6b, 0x9e, 0x93, 0x91, 0xd1, 0x58, 0x1e, 0xa5, 0xa2,
	0xaf, 0xd2, 0xda, 0xd9, 0x17, 0x48, 0xf7, 0x88, 0x99, 0x95, 0xd2, 0xba, 0x65, 0xb2, 0x66, 0xc5,
	0x33, 0x71, 0x36, 0x14, 0x94, 0x0b, 0xaa, 0xce, 0xb2, 0x92, 0x95, 0x41, 0xef, 0x2d, 0x80, 0x59,
	0x16, 0xcf, 0x94, 0xab, 0x83, 0x0a, 0x88, 0xff, 0x6b, 0x2d, 0x4d, 0x7b, 0x6c, 0x1b, 0xd2, 0xa5,
	0xa5, 0xf2, 0x29, 0x8b, 0x28, 0x4b, 0x97, 0xbc, 0x4c, 0xd6, 0x69, 0x05, 0xc1, 0xa1, 0xb5, 0x46,
	0x33, 0x95, 0xa6, 0x2d, 0x81, 0xfa, 0x41, 0x9f, 0xeb, 0x79, 0x96, 0x9b, 0xb9, 0xa6, 0x2e, 0xa3,
	0x3a, 0x5a, 0x84, 0xa5, 0x7a, 0x3a, 0x23, 0x42, 0x2f, 0x1a, 0x61, 0xda, 0xd4, 0x25, 0xd0, 0xff,
	0xa7, 0x01, 0x57, 0xed, 0x21, 0x53, 0xcc, 0x8d, 0x1c, 0x9e, 0xf9, 0xd9, 0x2f, 0x4e, 0x0e, 0xe8,
	0x06, 0x1b, 0x8b, 0xe0, 0x98, 0x88, 0x39, 0x0d, 0x5c, 0x42, 0x77, 0xd4, 0x05, 0x5c, 0x53, 0x74,
	0x2c, 0x02, 0x34, 0x73, 0xb4, 0x71, 0x5f, 0xd7, 0x12, 0xf6, 0xf2, 0x4d, 0xb8, 0x79, 0xf9, 0x4d,
	0xb8, 0x75, 0xf9, 0x4d, 0x78, 0xe5, 0xf2, 0x9b, 0xf0, 0xea, 0xe5, 0x36, 0xe1, 0xf6, 0x4b, 0x36,
	0x61, 0xef, 0x11, 0xac, 0x8b, 0x78, 0x6e, 0x5a, 0xc7, 0xd0, 0xa8, 0xd7, 0x31, 0x6d, 0x75, 0xa3,
	0xd2, 0x56, 0x6e, 0x0b, 0x41, 0x65, 0x63, 0xff, 0xf7, 0x3a, 0x78, 0x88, 0x4c, 0xa8, 0xde, 0xd7,
	0x10, 0x79, 0x96, 0x10, 0xa9, 0xf6, 0xfb, 0x47, 0x9a, 0x8a, 0x41, 0x44, 0x09, 0x53, 0xee, 0x8d,
	0x3b, 0x28, 0x93, 0xbd, 0x8f, 0x61, 0x5d, 0xa6, 0x4c, 0x32, 0x09, 0xeb, 0xd5, 0x2d, 0xb6, 0xca,
	0x6c, 0x54, 0x76, 0xf0, 0x3e, 0x00, 0x08, 0xaa, 0xc3, 0x64, 0xc1, 0xbd, 0x30, 0x07, 0x0a, 0xd6,
	0xda, 0xb7, 0xd0, 0x59, 0xcd, 0xe5, 0xbe, 0x79, 0x2f, 0x17, 0xbb, 0xce, 0xfb, 0xb0, 0xb0, 0x7a,
	0xb7, 0x8c, 0xe7, 0xdb, 0xb9, 0xe7, 0xd2, 0x6d, 0x3d, 0xdf, 0xbf, 0xfd, 0xbf, 0xea, 0x70, 0x2d,
	0xaf, 0x94, 0x9c, 0x71, 0x26, 0xc9, 0x51, 0x7f, 0x5f, 0x8f, 0x16, 0x22, 0xc4, 0x80, 0x87, 0xc4,
	0x75, 0x43, 0x2a, 0xea, 0xdf, 0x86, 0x44, 0x88, 0x23, 0x39, 0x71, 0x9b, 0xaa, 0x93, 0x5e, 0xe9,
	0xfa, 0x1f, 0x41, 0x97, 0xe7, 0xcd, 0xe8, 0xee, 0x7f, 0xbb, 0xea, 0x5c, 0xe8, 0x57, 0x54, 0xb4,
	0xaf, 0x54, 0xaf, 0x75, 0xa1, 0xea, 0x7d, 0x0a, 0x57, 0x70, 0x69, 0x97, 0x37, 0x9d, 0xd0, 0xed,
	0xdf, 0xa9, 0xd6, 0x70, 0xd9, 0xde, 0x8f, 0x2a, 0xbe, 0xfe, 0x6f, 0x75, 0xd8, 0x78, 0x42, 0xb0,
	0x50, 0x65, 0xd6, 0xd9, 0xef, 0x53, 0xce, 0xba, 0x54, 0x7e, 0x5d, 0x59, 0xf7, 0x77, 0x1d, 0x36,
	0x5d, 0x99, 0x5e, 0x43, 0xca, 0x7d, 0x05, 0x5b, 0xa3, 0x25, 0x64, 0xba, 0x10, 0xf1, 0x96, 0x46,
	0xf0, 0xbf, 0x81, 0x8d, 0x41, 0xc4, 0x25, 0x39, 0x27, 0xfb, 0x8a, 0x6f, 0x58, 0xbf, 0xe8, 0x1b,
	0x1e, 0xc0, 0xa6, 0xcb, 0xf5, 0x0a, 0x4f, 0xb8, 0xdf, 0xff, 0xfa, 0xfe, 0x84, 0xaa, 0xdd, 0x80,
	0x87, 0x64, 0x97, 0xe3, 0xdd, 0x80, 0xc7, 0xf7, 0x54, 0x38, 0xc2, 0xec, 0xf4, 0x9e, 0x4a, 0x46,
	0x24, 0x7e, 0x76, 0xd7, 0x0e, 0xe8, 0xbb, 0x13, 0x7e, 0x2f, 0x3d, 0xd9, 0x68, 0xc5, 0xfc, 0xf7,
	0xe0, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xbb, 0xa0, 0xae, 0x07, 0x13, 0x00, 0x00,
}
