{
 "title": "agent dashborad",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inlongGroupId",
    "label": "GroupId",
    "query": {
     "query": "{__name__=~\".*Source.*\",inlongGroupId=~\".+\"}"
    }
   },
   {
    "name": "inlongStreamId",
    "label": "StreamId",
    "query": {
     "query": "{__name__=~\".*Source.*\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\".*\",dimension=~\"(sourceSuccessCount|sourceFailCount)\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\",pluginId=~\".*Source.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reader",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\".*\",dimension=~\"(pluginReadCount|pluginReadFailCount|pluginReadSuccessCount)\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\",pluginId=~\".*Reader.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{__name__=~\".*\",dimension=~\"(pluginReadCount|pluginReadFailCount|pluginReadSuccessCount|pluginSendCount|pluginSendFailCount|pluginSendSuccessCount)\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\",pluginId=~\".*Channel.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sink",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{__name__=~\".*\",dimension=~\"(sinkFailCount|sinkSuccessCount)\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\",pluginId=~\".*Sink.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AgentTotal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Agent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "agent_total{job=\"agent\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "JobManager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{__name__=~\".*\",dimension=~\"(jobRunningCount|jobFatalCount)\",componentName=\"JobManager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TaskManager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "{__name__=~\".*\",dimension=~\"(taskRunningCount|taskRetryingCount|taskFatalCount)\",componentName=\"TaskManager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "JVM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{__name__=~\"jvm_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"process_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}