{
 "title": "Dataproxy dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inlongGroupId",
    "label": "GroupId",
    "query": {
     "query": "{__name__=~\".*Source.*\",inlongGroupId=~\".+\"}"
    }
   },
   {
    "name": "inlongStreamId",
    "label": "StreamId",
    "query": {
     "query": "{__name__=~\".*Source.*\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "读取成功数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"readSuccessCount\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "读取成功Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"readSuccessSize\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "读取失败数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"readFailCount\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "读取失败size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"readFailSize\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "发送数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"sendCount\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "发送数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"sendCount\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "发送成功数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"sendSuccessCount\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "发送成功数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"sendSuccessCount\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "发送失败数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"sendFailCount\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "发送失败数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"sendFailCount\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sinkDuration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"sinkDuration\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nodeDuration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"nodeDuration\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "wholeDuration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum({__name__=\"default_dataproxy_id_total\",dimension=\"wholeDuration\",inlongGroupId=~\"$inlongGroupId\",inlongStreamId=~\"$inlongStreamId\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "DP_READ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "default_dataproxy_total{dimension=~\"read.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DP_SEND",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "default_dataproxy_total{dimension=~\"send.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DP_DURATION",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "default_dataproxy_total{dimension=~\".*Duration\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}